get tkmain_tx32.tsc
get tkmain_tx45.tsc
get tkctdmlperfenh.tsc
get tkctdmlperfenh_01a.log 
get tkctdmlperfenh_01b.log 
get tkctdmlperfenh_01c.log 
get tkctdmlperfenh_01d.log 
get tkctdmlperfenhsetup_01.log 
get tkctautosync_02_1.sql 
get tkctdmlperfenh_01a.sql 
get tkctdmlperfenh_01b.sql 
get tkctdmlperfenh_01c.sql 
get tkctdmlperfenh_01d.sql 
get tkctdmlperfenhsetup_01.sql